services:
  backend-challenge-01-crud:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      backend-challenge-01-crud-db:
        condition: service_healthy

  backend-challenge-01-crud-db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
